language: node_js
node_js: 14.15.0
services:
- mongodb

install:
  - npm install -g newman

before_script:
  - node --version
  - npm --version
  - newman --version

script:
  - node ../asistenciasAPI/server/bd.js
  - newman run ../asistenciasAPI/server/tests/Backend.postman_environment.json -e ../asistenciasAPI/server/tests/Backend.postman_collection.json