language: node_js
node_js: 14.15.0
services:
- mongodb

install:
  - npm install -g newman

before_script:
  - node --version
  - npm --version
  - newman --version

script:
  - node /server/bd.js
  - newman run /server/tests/Backend.postman_environment.json -e /server/tests/Backend.postman_collection.json