language: node_js
node_js: 14.15.0
services:
- mongodb

install:
  - npm install -g newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

script:
  - newman run asistenciasAPI\server\tests/Backend.postman_environment.json
  - newman run asistenciasAPI\server\tests/Backend.postman_collection.json