language: node_js
node_js: 14.15.0
services:
- mongodb

install:
  - npm install -g newman

before_script:
  - node --version
  - npm --version
  - newman --version

script:
  - node ../asistenciasAPI/server/bd.js &
  - sleep 10
  - newman run https://www.getpostman.com/collections/79b7dcc81f6ddb4b674e &
  - sleep 10
  - cd ../asistenciasAPI/server/tests/&
  - newman run Backend.postman_environment.json -e Backend.postman_collection.json&