language: node_js
node_js: 14.15.0
services:
- mongodb

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version
script:
  - node_modules/.bin/newman run tests/Backend.postman_collection.json -e tests/Backend.postman_environment.json